const LOCALIZED_STRINGS = {
  'en': ENGLISH,
  'zh': CHINESE_SIMPLIFIED,
  'zh_Hans': CHINESE_SIMPLIFIED,
  'zh_Hant': CHINESE_TRADITIONAL,
};

const ENGLISH = {
  'connect_5': 'Connect 5',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'done': 'Done',
  'ok': 'OK',

  // Start menu
  'continue_game': 'Continue Game',
  'new_game': 'New Game',
  'replays': 'Replays',

  // Settings
  'settings': 'Settings',
  'general': 'General',
  'change_language': 'Change Language',
  'language': 'Language',
  'game': 'Game',
  'double_tap_to_confirm': 'Double Tap to Confirm',
  'highlight_last_step': 'Highlight Last Step',
  'highlight_winning_moves': 'Highlight Winning Moves',
  'board_size': 'Board Size',
  'appearance': 'Appearance',
  'dark_mode': 'Dark Mode',
  'accent': 'Accent',
  'board_theme': 'Board Theme',

  // Game
  'start_new_game': 'Start New Game',
  'two_players': 'Two Players',
  'bot_black': 'Bot (Black)',
  'bot_white': 'Bot (White)',
  'restart_game': 'Restart Game',
  'quit': 'Quit',
  'black_victory': 'Black Victory',
  'white_victory': 'White Victory',
  'tie': 'Tie',

  // Replays
  'steps': 'steps',
  'no_replays_message': 'There are currently no replays saved. Whenever you finish a game, it will be saved here.',

  // Stats
  'stats': 'Stats',
  'total_games_played': 'Total Games Played',
  'total_black_victory': 'Total Black Victory',
  'total_white_victory': 'Total White Victory',
  'games_played': 'Games Played',
  'games_won': 'Games Won',
  'games_lost': 'Games Lost',
  'win_rate': 'Win Rate',
  'player_vs_bot_black': 'Player vs Bot (Black)',
  'player_vs_bot_white': 'Player vs Bot (White)',
  'clear_stats': 'Clear Stats',
  'clear_stats_alert_message': 'Are you sure you want to clear stats? They will be permanently deleted.',

  // Help
  'help': 'Help',
  'help_message': 'Two players put down pieces on the board alternately. The first player who connects 5 pieces in a row wins.',

  // Accents
  'accent_blue': 'Blue',
  'accent_red': 'Red',
  'accent_green': 'Green',
  'accent_orange': 'Orange',
  'accent_grey': 'Grey',

  // Board themes
  'board_theme_classic': 'Classic',
  'board_theme_classic_darker': 'Classic Darker',
  'board_theme_night': 'Night',
  'board_theme_blue': 'Blue',
  'board_theme_red': 'Red',
  'board_theme_green': 'Green',
  'board_theme_grey': 'Grey',

  // Multiplayer
  'multiplayer': 'Multiplayer',
  'multiplayer_as_black': 'Multiplayer as Black',
  'multiplayer_as_white': 'Multiplayer as White',
  'player_1': 'Player 1',
  'player_2': 'Player 2',
  'spectator': 'Spectator',
  'spectators': 'Spectators',
  'guest': 'Guest',
  'you': 'You',
  'rooms': 'Rooms',
  'room_info': 'Room Info',
  'room_id': 'Room ID',
  'room_settings': 'Room Settings',
  'allow_spectators': 'Allow Spectators',
  'public_room': 'Public Room',
  'no_rooms_message': 'No rooms at the moment. You can create one!',
  'join': 'Join',
  'join_room': 'Join Room',
  'join_room_by_id': 'Join Room by ID',
  'create_room': 'Create Room',
  'not_allowed': 'Not Allowed',
  'search': 'Search',
  'restart': 'Restart',
  'nickname': 'Nickname',
  'spectating': 'Spectating',
  'connection_take_a_while': 'Getting rooms. This may take a while...',

  // Multiplayer errors
  'connection_failed': 'Connection Failed',
  'connection_failed_message': 'Cannot connect to server. Please check your internet connection and try again later.',
  'invalid_room_id': 'Invalid Room ID',
  'invalid_room_id_message': 'The room ID is invalid. Please try another one.',
  'room_id_taken': 'Room ID Taken',
  'room_id_taken_message': 'The room ID is already being used by a room. Please try another one.',
  'cannot_create_room': 'Cannot Create Room',
  'cannot_create_room_message': 'Unable to create a room. Please check your internet connection and try again later.',
  'join_invalid_role': 'Cannot Join with Role',
  'join_invalid_role_message': 'Cannot join room with role. It is likely that another player has already taken the spot.',
  'join_invalid_room_id': 'Invalid Room ID',
  'join_invalid_room_id_message': 'Cannot join room with ID. The room was probably deleted by the owner.',
  'join_connection_timeout': 'Connection Timeout',
  'join_connection_timeout_message': 'The connection has timed out. Please check your internet connection and try again.',
  'cannot_join_room': 'Cannot Join Room',
  'cannot_join_room_message': 'Unable to join the room. Please check your internet connection and try again later.',
  'room_not_found': 'Room Not Found',
  'room_not_found_message': 'The room with given room ID is not found. Please verify that the ID entered is correct.',
  'cannot_get_room': 'Cannot Get Room',
  'cannot_get_room_message': 'Unable to get room with ID. Please check your internet connection and try again later.',

  // Event messages
  '\$user_\$role_joined_message': '\$role - \$user joined the room.',
  '\$user_left_message': '\$user left the room.',
  'reconnected_message': 'You have reconnected to the game.',
  '\$user_reconnected_message': '\$user has reconnected to the game.',
  '\$user_disconnected_message': '\$user has disconnected.',
  'game_started_message': 'The game has started!',
  'game_ended_message': 'The game has ended.',
  'waiting_opponent_restart_message': 'Waiting for opponent to restart...',
  '\$user_set_restart_message': '\$user chooses to restart!',
  'your_turn': 'Your turn!',
  'waiting_opponent_turn': 'Waiting for opponent\'s turn...',
  'waiting_opponent_reconnect': 'Waiting for opponent to reconnect...',
};

const CHINESE_SIMPLIFIED = {
  'connect_5': '五子棋',
  'cancel': '取消',
  'confirm': '确认',
  'done': '完成',
  'ok': 'OK',

  // Start menu
  'continue_game': '继续游戏',
  'new_game': '新游戏',
  'replays': '游戏回放',

  // Settings
  'settings': '设置',
  'general': '通用',
  'change_language': '切换语言',
  'language': '语言',
  'game': '游戏',
  'double_tap_to_confirm': '双击确认落子',
  'highlight_last_step': '标记上一步',
  'highlight_winning_moves': '标记胜利棋子',
  'board_size': '棋盘大小',
  'appearance': '外貌',
  'dark_mode': '黑夜模式',
  'accent': '色调',
  'board_theme': '棋盘色调',

  // Game
  'start_new_game': '开始新游戏',
  'two_players': '双人',
  'bot_black': '人机（黑棋）',
  'bot_white': '人机（白棋）',
  'restart_game': '重新开始',
  'quit': '退出',
  'black_victory': '黑棋胜利',
  'white_victory': '白棋胜利',
  'tie': '平局',

  // Replays
  'steps': '步',
  'no_replays_message': '目前没有任何游戏回放。当你完成一盘游戏时，它会被存在这里。',

  // Stats
  'stats': '数据',
  'total_games_played': '游戏总数',
  'total_black_victory': '黑棋胜利总数',
  'total_white_victory': '白棋胜利总数',
  'games_played': '游戏次数',
  'games_won': '胜利次数',
  'games_lost': '失败次数',
  'win_rate': '胜率',
  'player_vs_bot_black': '玩家 vs 人机（黑棋）',
  'player_vs_bot_white': '玩家 vs 人机（白棋）',
  'clear_stats': '清空数据',
  'clear_stats_alert_message': '确定要清空数据吗？它们会被永久删除。',

  // Help
  'help': '帮助',
  'help_message': '两个玩家轮流放在棋盘上放下一个棋子。第一个将五个棋子连成一条直线的玩家获胜。',

  // Accents
  'accent_blue': '蓝色',
  'accent_red': '红色',
  'accent_green': '绿色',
  'accent_orange': '橙色',
  'accent_grey': '灰色',

  // Board themes
  'board_theme_classic': '经典',
  'board_theme_classic_darker': '深色经典',
  'board_theme_night': '黑夜',
  'board_theme_blue': '蓝色',
  'board_theme_red': '红色',
  'board_theme_green': '绿色',
  'board_theme_grey': '灰色',

  // Multiplayer
  'multiplayer': '联机',
  'multiplayer_as_black': '联机执黑',
  'multiplayer_as_white': '联机执白',
  'player_1': '玩家1',
  'player_2': '玩家2',
  'spectator': '观众',
  'spectators': '观众',
  'guest': '玩家',
  'you': '你',
  'rooms': '房间',
  'room_info': '房间信息',
  'room_id': '房间ID',
  'room_settings': '房间设置',
  'allow_spectators': '允许观战',
  'public_room': '公开房间',
  'no_rooms_message': '目前没有任何房间。你可以创建一个新的房间！',
  'join': '加入',
  'join_room': '加入房间',
  'join_room_by_id': '通过ID加入房间',
  'create_room': '创建房间',
  'not_allowed': '不允许',
  'search': '搜索',
  'restart': '重新开始',
  'nickname': '昵称',
  'spectating': '观战中',
  'connection_take_a_while': '正在获取房间，请稍后片刻...',

  // Multiplayer errors
  'connection_failed': '连接失败',
  'connection_failed_message': '无法连接到服务器，请检查你的网络设置或稍后重试。',
  'invalid_room_id': '无效房间ID',
  'invalid_room_id_message': '无效房间ID，请尝试使用另外一个。',
  'room_id_taken': '房间ID已被使用',
  'room_id_taken_message': '房间ID已经被另外一个房间使用，请尝试另外一个。',
  'cannot_create_room': '无法创建房间',
  'cannot_create_room_message': '无法创建房间，请检查你的网络设置或稍后重试。',
  'join_invalid_role': '无法加入房间',
  'join_invalid_role_message': '无法加入房间，另外一个玩家已经占了这个位置。',
  'join_invalid_room_id': '无效房间ID',
  'join_invalid_room_id_message': '无法加入房间，这个房间可能已经被房主删除。',
  'join_connection_timeout': '连接超时',
  'join_connection_timeout_message': '当前连接已超时，请检查你的网络设置或稍后重试。',
  'cannot_join_room': '无法加入房间',
  'cannot_join_room_message': '无法加入房间，请检查你的网络设置或稍后重试。',
  'room_not_found': '无法找到房间',
  'room_not_found_message': '找不到拥有这个ID的房间，请检查你输入了正确的房间ID。',
  'cannot_get_room': '无法获取房间',
  'cannot_get_room_message': '无法获取房间，请检查你的网络设置或稍后重试。',

  // Event messages
  '\$user_\$role_joined_message': '\$role - \$user已加入房间。',
  '\$user_left_message': '\$user已退出房间。',
  'reconnected_message': '你已重新连接。',
  '\$user_reconnected_message': '\$user已重新连接。',
  '\$user_disconnected_message': '\$user失去了连接。',
  'game_started_message': '游戏开始！',
  'game_ended_message': '游戏已结束。',
  'waiting_opponent_restart_message': '等待对方重新开始...',
  '\$user_set_restart_message': '\$user选择了重新开始！',
  'your_turn': '你的回合！',
  'waiting_opponent_turn': '等待对方的回合...',
  'waiting_opponent_reconnect': '等待对方重新连接...',
};

const CHINESE_TRADITIONAL = {
  'connect_5': '五子棋',
  'cancel': '取消',
  'confirm': '確認',
  'done': '完成',
  'ok': 'OK',

  // Start menu
  'continue_game': '繼續遊戲',
  'new_game': '新遊戲',
  'replays': '遊戲回放',

  // Settings
  'settings': '設置',
  'general': '通用',
  'change_language': '切換語言',
  'language': '語言',
  'game': '遊戲',
  'double_tap_to_confirm': '雙擊確認落子',
  'highlight_last_step': '標記上一步',
  'highlight_winning_moves': '標記勝利棋子',
  'board_size': '棋盤大小',
  'appearance': '外貌',
  'dark_mode': '黑夜模式',
  'accent': '色調',
  'board_theme': '棋盤色調',

  // Game
  'start_new_game': '開始新遊戲',
  'two_players': '雙人',
  'bot_black': '人機（黑棋）',
  'bot_white': '人機（白棋）',
  'restart_game': '重新開始',
  'quit': '退出',
  'black_victory': '黑棋勝利',
  'white_victory': '白棋勝利',
  'tie': '平局',

  // Replays
  'steps': '步',
  'no_replays_message': '目前沒有任何遊戲回放。當你完成一盤遊戲時，它會被存在這裏。',

  // Stats
  'stats': '數據',
  'total_games_played': '遊戲總數',
  'total_black_victory': '黑棋勝利總數',
  'total_white_victory': '白棋勝利總數',
  'games_played': '遊戲次數',
  'games_won': '勝利次數',
  'games_lost': '失敗次數',
  'win_rate': '勝率',
  'player_vs_bot_black': '玩家 vs 人機（黑棋）',
  'player_vs_bot_white': '玩家 vs 人機（白棋）',
  'clear_stats': '清空數據',
  'clear_stats_alert_message': '確定要清空數據嗎？它們會被永久刪除。',

  // Help
  'help': '幫助',
  'help_message': '兩個玩家輪流放在棋盤上放下一個棋子。第一個將五個棋子連成一條直線的玩家獲勝。',

  // Accents
  'accent_blue': '藍色',
  'accent_red': '紅色',
  'accent_green': '綠色',
  'accent_orange': '橙色',
  'accent_grey': '灰色',

  // Board themes
  'board_theme_classic': '經典',
  'board_theme_classic_darker': '深色經典',
  'board_theme_night': '黑夜',
  'board_theme_blue': '藍色',
  'board_theme_red': '紅色',
  'board_theme_green': '綠色',
  'board_theme_grey': '灰色',

  // Multiplayer
  'multiplayer': '聯機',
  'multiplayer_as_black': '聯機執黑',
  'multiplayer_as_white': '聯機執白',
  'player_1': '玩家1',
  'player_2': '玩家2',
  'spectator': '觀眾',
  'spectators': '觀眾',
  'guest': '玩家',
  'you': '你',
  'rooms': '房間',
  'room_info': '房間信息',
  'room_id': '房間ID',
  'room_settings': '房間設置',
  'allow_spectators': '允許觀戰',
  'public_room': '公開房間',
  'no_rooms_message': '目前沒有任何房間。你可以創建一個新的房間！',
  'join': '加入',
  'join_room': '加入房間',
  'join_room_by_id': '通過ID加入房間',
  'create_room': '創建房間',
  'not_allowed': '不允許',
  'search': '搜索',
  'restart': '重新開始',
  'nickname': '昵稱',
  'spectating': '觀戰中',
  'connection_take_a_while': '正在獲取房間，請稍後片刻...',

  // Multiplayer errors
  'connection_failed': '連接失敗',
  'connection_failed_message': '無法連接到服務器，請檢查你的網絡設置或稍後重試。',
  'invalid_room_id': '無效房間ID',
  'invalid_room_id_message': '無效房間ID，請嘗試使用另外一個。',
  'room_id_taken': '房間ID已被使用',
  'room_id_taken_message': '房間ID已經被另外一個房間使用，請嘗試另外一個。',
  'cannot_create_room': '無法創建房間',
  'cannot_create_room_message': '無法創建房間，請檢查你的網絡設置或稍後重試。',
  'join_invalid_role': '無法加入房間',
  'join_invalid_role_message': '無法加入房間，另外一個玩家已經占了這個位置。',
  'join_invalid_room_id': '無效房間ID',
  'join_invalid_room_id_message': '無法加入房間，這個房間可能已經被房主刪除。',
  'join_connection_timeout': '連接超時',
  'join_connection_timeout_message': '當前連接已超時，請檢查你的網絡設置或稍後重試。',
  'cannot_join_room': '無法加入房間',
  'cannot_join_room_message': '無法加入房間，請檢查你的網絡設置或稍後重試。',
  'room_not_found': '無法找到房間',
  'room_not_found_message': '找不到擁有這個ID的房間，請檢查你輸入了正確的房間ID。',
  'cannot_get_room': '無法獲取房間',
  'cannot_get_room_message': '無法獲取房間，請檢查你的網絡設置或稍後重試。',

  // Event messages
  '\$user_\$role_joined_message': '\$role - \$user已加入房間。',
  '\$user_left_message': '\$user已退出房間。',
  'reconnected_message': '你已重新連接。',
  '\$user_reconnected_message': '\$user已重新連接。',
  '\$user_disconnected_message': '\$user失去了連接。',
  'game_started_message': '遊戲開始！',
  'game_ended_message': '遊戲已結束。',
  'waiting_opponent_restart_message': '等待對方重新開始...',
  '\$user_set_restart_message': '\$user選擇了重新開始！',
  'your_turn': '你的回合！',
  'waiting_opponent_turn': '等待對方的回合...',
  'waiting_opponent_reconnect': '等待對方重新連接...',
};
